# Generated by Django 2.0.13 on 2019-04-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20190408_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animalid',
        ),
    ]
